Changelog 140
intellij-rust/intellij-rust.github.io pull request #105
Opened 2021-01-29 15:15 UTC by vlad20012

2021-01-30 16:01 UTC, ortem commented on _posts/2021-02-01-changelog-140.markdown
> +* Fix `Change item visibility` intention so that it is not offered in trait impl blocks. (by [@Kobzol])
```suggestion
* Do not suggest `Change item visibility` intention in trait impl blocks (by [@Kobzol])
```

2021-02-01 09:13 UTC, Undin requested changes

2021-02-01 09:14 UTC, Undin reviewed
Oh, and let's add note about dropping 2020.2 support in next release
Something like "This is the last release that supports the 2020.2 platform. To receive plugin updates further, please upgrade your IDE to 2020.3."

2021-02-01 13:53 UTC, Undin commented on _posts/2021-02-01-changelog-140.markdown
> +  {% include gif-img.html path="/assets/posts/changelog-140/6563" w="700px" %}
Let's create a new gif where confirmation dialog is shown as well

2021-02-01 14:52 UTC, Undin approved these changes
LGTM

2021-02-01 14:53 UTC, merged